# Generated by Django 3.0.3 on 2020-02-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cow_space', '0002_auto_20200226_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='title',
            field=models.CharField(choices=[('GR', 'Green Zone'), ('GO', 'Gold Zone'), ('PR', 'Private Zone')], max_length=50),
        ),
    ]
